name: build
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write # This is required to push to GitHub registry
jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Docker Build 
        run: |
          DOCKER_BUILDKIT=1 docker build . --tag $IMAGE_NAME

      - name: Docker Push 
        run: |
          docker tag $IMAGE_NAME $IMAGE_REPO/$IMAGE_NAME:$VERSION
          docker push $IMAGE_REPO/$IMAGE_NAME:$VERSION

  build_with_nscloud:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud
    env:
      IMAGE_NAME: nsc-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Install and configure Namespace Cloud CLI
        uses: namespacelabs/nscloud-setup@v0.0.2

      - name: Build and push with Namespace Cloud cluster
        run: |
          nsc build . --push $IMAGE_REPO/$IMAGE_NAME --tag $VERSION