name: build-with-actions
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write # This is required to push to GitHub registry
jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}


  build_with_nscloud:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud
    env:
      IMAGE_NAME: nsc-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Namespace Cloud CLI
        uses: namespacelabs/nscloud-setup@v0.0.2

      - name: Set up Nanespace Cloud Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0.0.2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}